#!/usr/bin/env ruby

require_relative "../lib/taskloop"

# TaskLoop::Command.run(ARGV)
# TaskLoop::Command.run(["init"])
# print "\n"
# TaskLoop::Command.run(["lint"])
# print "\n"
# TaskLoop::Command.run(["list"])
# print "\n"
# TaskLoop::Command.run(["log"])
# print "\n"
# TaskLoop::Command.run(["launch"])
# TaskLoop::Command.run(["env", "--list"])
# TaskLoop::Command.run(["shutdown"])
TaskLoop::Command.run(["run"])
# print "\n"
# TaskLoop::Command.run(["register"])
# print "\n"
# TaskLoop::Command.run(["unregister"])
# print "\n"